### ISSUE TITLE
Premier message dans un channel non pris en compte

### ISSUE THREAD

**Issue by ltuffery** [DoubleV37/irc#27]
Quand un 2ieme User join le channel, le premier message qu'il envoie n'est pas broadcast au autre utilisateur
![Screenshot from 2023-11-03 18-36-03](https://github.com/DoubleV37/irc/assets/123221865/94e4f2a4-4a08-4b25-815a-f26ad5079f30)

**Comment by DoubleV37** [comment]
Je n'arrive pas à reproduire le bug, il s'est peut être résolu avec les derniers commits.

**Comment by ltuffery** [comment]
Fix dans les dernières version de main
