### ISSUE TITLE
Bonus : Bot

### ISSUE THREAD

**Issue by DoubleV37** [DoubleV37/irc#33]

**Comment by ltuffery** [comment]
Description ?

**Comment by DoubleV37** [comment]
Je t'invite à regarder le sujet 😉

**Comment by DoubleV37** [comment]
> Description ?

Je t'invite à regarder le sujet 😉

**Comment by ltuffery** [comment]
> > Description ?
> 
> Je t'invite à regarder le sujet 😉

Mais le but est de toute avoir au même endroit non ?

**Comment by DoubleV37** [comment]
> > > Description ?
> > 
> > 
> > Je t'invite à regarder le sujet 😉
> 
> Mais le but est de toute avoir au même endroit non ?

Le sujet n'a pas beaucoup d'instruction sur le comment. On voit ça demain sur le contenu.

**Comment by ltuffery** [comment]
> > > > Description ?
> > > 
> > > 
> > > Je t'invite à regarder le sujet 😉
> > 
> > Mais le but est de toute avoir au même endroit non ?
> 
> Le sujet n'a pas beaucoup d'instruction sur le comment. On voit ça demain sur le contenu.

Ouais mais la c'est pas savoir le comment mais le pourquoi non ?

**Comment by DoubleV37** [comment]
> > > > > Description ?
> > > > 
> > > > 
> > > > Je t'invite à regarder le sujet 😉
> > > 
> > > 
> > > Mais le but est de toute avoir au même endroit non ?
> > 
> > 
> > Le sujet n'a pas beaucoup d'instruction sur le comment. On voit ça demain sur le contenu.
> 
> Ouais mais la c'est pas savoir le comment mais le pourquoi non ?

le pourquoi ? faire le bonus

**Comment by ltuffery** [comment]
> > > > > > Description ?
> > > > > 
> > > > > 
> > > > > Je t'invite à regarder le sujet 😉
> > > > 
> > > > 
> > > > Mais le but est de toute avoir au même endroit non ?
> > > 
> > > 
> > > Le sujet n'a pas beaucoup d'instruction sur le comment. On voit ça demain sur le contenu.
> > 
> > Ouais mais la c'est pas savoir le comment mais le pourquoi non ?
> 
> le pourquoi ? faire le bonus

Non mais ok pour ça, mais que devra faire le bot ?
